### ISSUE TITLE
Git commands not working with current syntax

### ISSUE THREAD

**Issue by jersearls** [jasonkarns/dotfiles#1]
Hey Jason, I'm adopting a similar solution for my dotfiles, however I was having issues with the way that your commands are currently structured. 

Specifically:
```(bash)
git config core.worktree="../../"
git config core.sparsecheckout=true
```

The equals sign was throwing a "key" error, removing it seemed to work with both commands:
```(bash)
git config core.worktree "$HOME"
git config core.sparsecheckout true
```
It was also confusing what directory you were starting from, and the working directory of the relative path that you set. `../../` so I set it to home instead. 

Thanks for doing the heavy lifting, I think this is a great solution to a complicated issue.

**Comment by jasonkarns** [comment]
Thanks! Not sure if old versions of git accepted the `key=value` form at one point, or if this has been wrong forever.

So if you set it using `git config core.worktree "$HOME"`, then the value of HOME would have been evaluated at the time you run the command (and the actual value in git's config file would be fixed). Do you know if the value there can use `~` directly and allow git to do the expansion? Just curious.

**Comment by jasonkarns** [comment]
(Just checked, git doesn't seem to do any tilde expansion for the worktree value, so `git config core.worktree ~` doesn't work. Looks like your variant is necessary
